apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: hello-world
  namespace: default
spec:
  tag: <DOCKER_USERNAME>/tutorial1
  serviceAccountName: tutorial-service-account
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/sample-accelerators/hello-world
      revision: main
